from pathlib import Path
from datetime import datetime
import re


BASE_DIR = Path(__file__).resolve().parent

OUTPUT_FILE = BASE_DIR / "_technology-amplifier-bundle.md"

SERIES_TITLE = "Technology as Structural Amplifier｜Internal Bundle"

COPYRIGHT_NOTICE = """## Copyright Notice

This document and the essays in this directory are English notes and theoretical materials of Longview Archive｜观势档案.

Unless otherwise stated, all contents are original works by the author. They may not be reproduced, excerpted, rewritten, translated, used for training, commercialized, or republished in any form without permission.

If platform-published versions differ from this archive, the archived version in this repository should be treated as the reference version.
"""


def slugify(text: str) -> str:
    text = text.lower()
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"\s+", "-", text)
    text = re.sub(r"-+", "-", text)
    return text.strip("-")


def extract_title(path: Path) -> str:
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("# "):
            return line.replace("# ", "").strip()
    return path.stem


def numbered_key(path: Path) -> int:
    match = re.match(r"^(\d+)-", path.name)
    if match:
        return int(match.group(1))
    return 999


def collect_files() -> list[Path]:
    files = []

    index_file = BASE_DIR / "index.md"
    if index_file.exists():
        files.append(index_file)

    numbered_files = sorted(
        [
            p
            for p in BASE_DIR.glob("*.md")
            if re.match(r"^\d{2}-.*\.md$", p.name)
            and not p.name.startswith("_")
        ],
        key=numbered_key,
    )

    files.extend(numbered_files)
    return files


def expected_missing(files: list[Path]) -> list[str]:
    existing = set()

    for path in files:
        match = re.match(r"^(\d{2})-", path.name)
        if match:
            existing.add(match.group(1))

    expected = {f"{i:02d}" for i in range(1, 12)}
    missing = sorted(expected - existing)

    return missing


def build_bundle() -> None:
    files = collect_files()

    if not files:
        raise RuntimeError("No markdown files found.")

    missing = expected_missing(files)

    lines = []

    lines.append(f"# {SERIES_TITLE}")
    lines.append("")
    lines.append(
        "This document is automatically generated by `build.py` for internal archive review, structural checking, and bundle preview."
    )
    lines.append("")
    lines.append(f"Generated at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append("")
    lines.append(f"Source directory: `{BASE_DIR}`")
    lines.append("")

    if missing:
        lines.append("## Build Warning")
        lines.append("")
        lines.append(
            "The following expected article numbers are missing:"
        )
        lines.append("")
        for item in missing:
            lines.append(f"- {item}")
        lines.append("")

    lines.append("## Table of Contents")
    lines.append("")

    for path in files:
        title = extract_title(path)
        anchor = f"file-{slugify(path.name)}"

        if path.name == "index.md":
            label = "0. [Index]"
        else:
            number_match = re.match(r"^(\d{2})-", path.name)
            number = number_match.group(1) if number_match else "--"
            label = f"{number}. [{title}]"

        lines.append(f"{label}(#{anchor})")

    lines.append("")
    lines.append("---")
    lines.append("")

    for path in files:
        anchor = f"file-{slugify(path.name)}"
        content = path.read_text(encoding="utf-8").strip()

        lines.append(f'<a id="{anchor}"></a>')
        lines.append("")
        lines.append(f"<!-- FILE: {path.name} -->")
        lines.append("")
        lines.append(content)
        lines.append("")
        lines.append("---")
        lines.append("")

    lines.append(COPYRIGHT_NOTICE.strip())
    lines.append("")

    OUTPUT_FILE.write_text("\n".join(lines), encoding="utf-8")

    print(f"Bundle generated: {OUTPUT_FILE}")
    print(f"Files included: {len(files)}")

    if missing:
        print(f"Warning: missing article numbers: {', '.join(missing)}")


if __name__ == "__main__":
    build_bundle()
