from __future__ import annotations

from pathlib import Path
import sys


BASE_DIR = Path(__file__).resolve().parent

FILES = [
    "index.md",
    "00-methodological-memorandum.md",
    "from-geography-to-consumption.md",
    "01-western-economics.md",
    "02-chinese-governance.md",
    "03-failure.md",
    "04-system-contribution.md",
    "05-consumption.md",
    "06-market-generation.md",
    "07-inefficiency.md",
    "08-correction.md",
    "09-modernization.md",
    "10-why-globalization.md",
    "11-why-globalization-retreat.md",
]

OUTPUT_FILE = "_productive-forces-economics-bundle.md"

# Internal review bundle: remove repeated author/copyright footers from each source file.
# Set to False if you want the source files concatenated exactly as written.
STRIP_REPEATED_FOOTERS = True

FOOTER_MARKERS = (
    "\n---\n\nEvan Vale",
    "\n---\n\nAster Vale",
    "\n---\n\n星衡｜Aster Vale",
)


def read_markdown(path: Path) -> str:
    """Read Markdown safely, including files saved with a UTF-8 BOM."""
    return path.read_text(encoding="utf-8-sig").strip()


def strip_footer(text: str) -> str:
    """Remove the repeated author/copyright footer from a standalone essay."""
    if not STRIP_REPEATED_FOOTERS:
        return text.rstrip()

    positions = []
    for marker in FOOTER_MARKERS:
        position = text.find(marker)
        if position != -1:
            positions.append(position)

    if not positions:
        return text.rstrip()

    return text[: min(positions)].rstrip()


def validate_sources() -> list[Path]:
    paths = [BASE_DIR / filename for filename in FILES]
    missing = [path.name for path in paths if not path.is_file()]

    if missing:
        print("Build failed. Missing files:", file=sys.stderr)
        for filename in missing:
            print(f"  - {filename}", file=sys.stderr)
        raise SystemExit(1)

    return paths


def build_bundle() -> Path:
    source_paths = validate_sources()
    sections: list[str] = []

    for path in source_paths:
        content = strip_footer(read_markdown(path))
        sections.append(content)

    bundle_header = """<!--
Internal review bundle generated by build.py.
Do not edit this file directly.
Edit the individual source files and run build.py again.
-->

# Productive-Forces Economics｜Complete Review Bundle

"""

    bundle = bundle_header + "\n\n---\n\n".join(sections)
    bundle = bundle.rstrip() + "\n"

    output_path = BASE_DIR / OUTPUT_FILE
    output_path.write_text(bundle, encoding="utf-8")

    return output_path


def main() -> None:
    output_path = build_bundle()
    size_kb = output_path.stat().st_size / 1024
    print(f"Built: {output_path.name}")
    print(f"Sources: {len(FILES)}")
    print(f"Size: {size_kb:.1f} KB")


if __name__ == "__main__":
    main()
