#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Create ONE local-only English review bundle from independent Markdown sources.

Read order: overview -> rules -> terms -> chapters 00 through 10.
Output: one directory ABOVE this script; never under the public docs folder.
Does not change source Markdown, mkdocs.yml, Git state, or old bundles.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUTPUT = HERE.parent / '_The_Economics_of_Productive_Organisation_EN_Complete.md'
PREFIXES = [f'{i:02d}-' for i in range(11)]


def chapters() -> list[Path]:
    result: list[Path] = []
    for prefix in PREFIXES:
        found = [p for p in HERE.glob(prefix + '*.md') if p.is_file()]
        if len(found) != 1:
            raise RuntimeError(
                f'Expected exactly one source for chapter {prefix}: found {len(found)}: {found}'
            )
        result.append(found[0])
    return result


def main() -> int:
    front = [HERE / 'index.md', HERE / 'Reading_and_Verification_Rules.md', HERE / 'Core_Terms.md']
    sources = front + chapters()
    for path in sources:
        if not path.is_file():
            raise FileNotFoundError(path)

    blocks = [
        '<!--\nGenerated by build_organisation_economics_en.py for LOCAL REVIEW ONLY.\n'
        'Edit independent sources, not this bundle. Do not copy it into website docs/.\n-->',
        '# The Economics of Productive Organisation｜English Complete Review Bundle',
        f'> Sources: {len(sources)} (overview + rules + terms + chapters 00–10)',
    ]
    for path in sources:
        content = path.read_text(encoding='utf-8-sig').strip()
        if not re.search(r'^#\s+\S', content, re.MULTILINE):
            raise ValueError(f'No H1 title found: {path.name}')
        blocks.append(f'<!-- SOURCE: {path.name} -->\n\n{content}')

    OUTPUT.write_text('\n\n---\n\n'.join(blocks).rstrip() + '\n', encoding='utf-8')
    print(f'OK: {OUTPUT}\nIndependent source files: {len(sources)}')
    return 0


if __name__ == '__main__':
    try:
        raise SystemExit(main())
    except (OSError, RuntimeError, ValueError) as error:
        print(f'ERROR: {error}', file=sys.stderr)
        raise SystemExit(2)
