# build.py
# Build an internal bundle for the Development series.
# Put this file in:
# docs/essays/notes/english/Development/

from pathlib import Path
from datetime import datetime

BASE_DIR = Path(__file__).resolve().parent

OUTPUT_FILE = BASE_DIR / "_development-bundle.md"

SERIES_TITLE = "Production: The Boundaries of Development｜Internal Bundle"

COPYRIGHT_NOTICE = """---

Copyright notice: This bundle and the essays included in it are internal working materials of Longview Archive｜观势档案.

Unless otherwise stated, all contents are original works by the author. They may not be reproduced, excerpted, rewritten, translated, used for training, commercialized, or republished in any form without permission.

If platform-published versions differ from this archive, the archived version in this repository should be treated as the reference version.
"""


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8").strip()


def get_article_files() -> list[Path]:
    """
    Collect article files from 01-*.md to 11-*.md.
    Excludes index.md, build.py, bundle outputs, and any non-numbered notes.
    """
    files = []

    for path in BASE_DIR.glob("*.md"):
        name = path.name

        if name == "index.md":
            continue

        if name.startswith("_"):
            continue

        if name in {"collected.md", "bundle.md"}:
            continue

        prefix = name[:2]

        if prefix.isdigit():
            number = int(prefix)
            if 1 <= number <= 11:
                files.append(path)

    return sorted(files, key=lambda p: p.name)


def extract_title(path: Path) -> str:
    """
    Extract the first Markdown H1 title from a file.
    If no H1 is found, fall back to filename.
    """
    text = read_text(path)

    for line in text.splitlines():
        line = line.strip()
        if line.startswith("# "):
            return line[2:].strip()

    return path.stem


def make_anchor(filename: str) -> str:
    """
    Internal simple anchor used in this generated bundle.
    """
    safe = filename.lower()
    safe = safe.replace(".", "")
    safe = safe.replace("_", "-")
    safe = safe.replace(" ", "-")
    safe = safe.replace("’", "")
    safe = safe.replace("'", "")
    return f"file-{safe}"


def make_toc(article_files: list[Path]) -> str:
    lines = ["## Table of Contents", ""]

    lines.append("0. [Index](#file-indexmd)")

    for path in article_files:
        title = extract_title(path)
        anchor = make_anchor(path.name)
        lines.append(f"{path.name[:2]}. [{title}](#{anchor})")

    return "\n".join(lines)


def make_file_block(path: Path) -> str:
    filename = path.name
    anchor = make_anchor(filename)
    content = read_text(path)

    return f"""---

<a id="{anchor}"></a>

<!-- FILE: {filename} -->

{content}
"""


def build_bundle() -> None:
    index_path = BASE_DIR / "index.md"

    if not index_path.exists():
        raise FileNotFoundError(f"Missing index.md in {BASE_DIR}")

    article_files = get_article_files()

    expected_numbers = {f"{i:02d}" for i in range(1, 12)}
    found_numbers = {p.name[:2] for p in article_files}
    missing = sorted(expected_numbers - found_numbers)

    extra_numbered = []
    for path in BASE_DIR.glob("*.md"):
        name = path.name
        if name[:2].isdigit():
            number = int(name[:2])
            if number < 1 or number > 11:
                extra_numbered.append(name)

    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    parts = []

    parts.append(f"# {SERIES_TITLE}")
    parts.append("")
    parts.append("This document is automatically generated by `build.py` for internal archive review, structural checking, and bundle preview.")
    parts.append("")
    parts.append(f"Generated at: {now}")
    parts.append("")
    parts.append(f"Source directory: `{BASE_DIR.as_posix()}`")
    parts.append("")

    if missing or extra_numbered:
        parts.append("## Build Warning")
        parts.append("")

        if missing:
            parts.append("The following expected article numbers are missing:")
            parts.append("")
            for number in missing:
                parts.append(f"- {number}")
            parts.append("")

        if extra_numbered:
            parts.append("The following numbered files are outside the expected 01–11 range:")
            parts.append("")
            for name in sorted(extra_numbered):
                parts.append(f"- {name}")
            parts.append("")

    parts.append(make_toc(article_files))

    parts.append("")
    parts.append("---")
    parts.append("")
    parts.append(f'<a id="{make_anchor("index.md")}"></a>')
    parts.append("")
    parts.append("<!-- FILE: index.md -->")
    parts.append("")
    parts.append(read_text(index_path))
    parts.append("")

    for path in article_files:
        parts.append(make_file_block(path))

    parts.append(COPYRIGHT_NOTICE)

    OUTPUT_FILE.write_text("\n".join(parts).strip() + "\n", encoding="utf-8")

    print(f"Built: {OUTPUT_FILE}")
    print(f"Articles included: {len(article_files)}")

    if missing:
        print(f"Warning: missing article numbers: {', '.join(missing)}")

    if extra_numbered:
        print(f"Warning: extra numbered files: {', '.join(sorted(extra_numbered))}")


if __name__ == "__main__":
    build_bundle()
